import { Mulish } from 'next/font/google'
import '@/app/ui/globals.css'
import { inter } from '@/app/ui/fonts';
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/footer';


//  we will find how to use this mulish in body as a css class.
export const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap'
});

 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className } >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
